name: Format
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
      - 'releases/**'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD Commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run Prettier in Client
        run: npx prettier --config ../.prettierrc --ignore-path ../.prettierignore -u --write .
        working-directory: client

      - name: Run Prettier in Server
        run: npx prettier --config ../.prettierrc --ignore-path ../.prettierignore -u --write .
        working-directory: server

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style: 🎨 Formatted Client & Server Code'
          branch: ${{ github.head_ref }}
